version: "3.9"
services:
  app:
    build: .
    container_name: mospi-app
    ports:
      - "8501:8501"
    environment:
      - SCRAPER_MAX_PAGES_PER_SEED=5
      - SCRAPER_RESPECT_ROBOTS=false
      - SCRAPER_RATE_LIMIT_SECONDS=0.5
      - SCRAPER_USER_AGENT=MoSPI-Scraper/1.0 (docker-compose)
    volumes:
      - ./data:/app/data
    command: streamlit run rag/ui/app.py --server.port 8501 --server.headless true

  db_viewer:
    build: .
    container_name: mospi-db-viewer
    ports:
      - "8502:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./data:/app/data
    command: streamlit run rag/ui/database_viewer.py --server.port 8501 --server.headless true
